name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      statuses: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check code style
        uses: reviewdog/action-shfmt@v1.0.4
      - name: Run static analysis
        uses: reviewdog/action-shellcheck@v1.29.0
      - name: Run tests
        run: |
          # workaround for https://github.com/actions/runner-images/issues/9644
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          npm install -g bats@1.11.0
          bats --report-formatter junit . completion/bash
      - name: Create test report 
        uses: dorny/test-reporter@v2.0.0
        if: always()
        with:
          name: Test report
          path: report.xml
          reporter: java-junit
