name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check code style
        uses: reviewdog/action-shfmt@v1.0.2
      - name: Run static analysis
        uses: reviewdog/action-shellcheck@v1.15.0
      - name: Set up bats
        run: npm install -g bats@1.8.0
      - name: Run tests
        run: bats --report-formatter junit up.bats
      - name: Create test report 
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Test report
          path: report.xml
          reporter: java-junit
