name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      statuses: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check code style
        uses: reviewdog/action-shfmt@v1.0.2
      - name: Run static analysis
        uses: reviewdog/action-shellcheck@v1.19.0
      - name: Set up bats
        run: npm install -g bats@1.8.0
      - name: Run tests
        run: bats --report-formatter junit . completion/bash
      - name: Create test report 
        uses: dorny/test-reporter@v1.7.0
        if: always()
        with:
          name: Test report
          path: report.xml
          reporter: java-junit
