name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check code style
        uses: reviewdog/action-shfmt@v1.0.2
      - name: Run static analysis
        uses: reviewdog/action-shellcheck@v1
      - name: Set up bats
        run: apt-get install -y bats@1.8.0
      - name: Run tests
        run: bats up.bats
